name: Check

on: [push]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
         distribution: 'adopt'
         java-version: '11'

      - name: Build the project
        run: ./gradlew build lint -PcatsApiKey=${{ secrets.CATS_API_KEY }} --stacktrace

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-reports
          path: |
            androidApp/build/reports
            shared/build/reports
