name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Java JDK
      uses: actions/setup-java@v2.1.0
      with:
       distribution: 'adopt'
       java-version: '11'
    - name: Build the project
      env: # Or as an environment variable
        catsApiKey: ${{ secrets.CATS_API_KEY }}
      run: ./gradlew assemble
