name: Check

on: [push]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set CI gradle.properties
        env:
          CATS_API_KEY: ${{ secrets.CATS_API_KEY }}
        run: |
          mkdir -p ~/.gradle
          cp .github/ci-gradle.properties ~/.gradle/gradle.properties
          echo "\ncatsApiKey=${CATS_API_KEY}" >> ~/.gradle/gradle.properties

      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
         distribution: 'adopt'
         java-version: '11'

      - name: Build the project
        run: ./gradlew build lint -PcatsApiKey= --stacktrace

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-reports
          path: |
            androidApp/build/reports
            shared/build/reports

      - name: Select Xcode
        uses: devbotsxyz/xcode-select@v1

      - name: Xcode build
        run: xcodebuild -project "iosApp/iosApp.xcodeproj" -scheme iosApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8'